version: 2
jobs:
  build:
    branches:
      only:
        - recaptcha
        - /rc-.*/

    docker:
      - image: circleci/node:10

    working_directory: ~/apek
    parallelism: 4

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v2-cache-packages-{{ checksum "yarn.lock" }}
            - v2-cache-packages-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Packages Cache
          key: v2-cache-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - restore_cache:
          name: Restore Build and Deploy Cache
          keys:
            - v2-build-deploy-cache-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
            - v2-build-deploy-cache-

      - run:
          name: Build
          command: yarn build

      - run:
          name: Deploy
          command: yarn firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT -m "$(git log -1 --pretty=%B)"

      - save_cache:
          name: Save Build and Deploy Cache
          key: v2-build-deploy-cache-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - .firebase
