version: 2
jobs:
  build:
    branch:
      only:
        - master

    docker:
      - image: circleci/node:10

    working_directory: ~/apek
    parallelism: 4

    steps:
      - checkout

      - restore_cache:
          name: Restore Firebase Deploy Cache
          keys:
            - firebase-deploy-cache-

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - cache-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: Build
          command: yarn vuepress build docs -d dist

      - run:
          name: Deploy
          command: yarn firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT -m "$(git log -1 --pretty=%B)"

      - save_cache:
          name: Save Firebase Deploy Cache
          key: firebase-deploy-cache-{{ checksum ".firebase/hosting.ZGlzdA.cache" }}
          paths:
            - .firebase

      - save_cache:
          name: Save Cache
          key: cache-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn