[install]
  command = "npm ci"
[build]
  publish = "dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "8"
  NPM_VERSION = "6.3.0"

[[redirects]]
from = "https://apek-stage.netlify.com/*"
to = "https://stage.apek.or.id/:splat"
status = 301
force = true
[[redirects]]
from = "http://apek-stage.netlify.com/*"
to = "https://stage.apek.or.id/:splat"
status = 301
force = true